import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Victoria Commercial Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layouts">
        <div className="childrens">

          {children}

        </div>
      </body>
    </html>
  );
}
